### ISSUE TITLE
How to proceed

### ISSUE THREAD

**Issue by hseeberger** [guillaumebreton/play-json-support#1]
Hey,

Now that the akka community project has been deleted, let's decide how to proceed. One possibility is having multiple projects (your, mine, others), each supporting one particular JSON library. An alternative would be to have one project supporting multiple libraries. For the latter the name clearly can't be pay-json-support. BTW, there's a PR for adding Json4s/Jackson to my project: https://github.com/hseeberger/akka-http-json/pull/20

What do you think?

Heiko

**Comment by guillaumebreton** [comment]
Hey @hseeberger, 

Your repository already has support for play-json, so PR it seems useless to me (unless I missed something) and obviously a multi-json framework could not be named "play-json-support" :wink: I do not really see what I can do here. 

BTW I am glad you got a PR for Json4s and Jakson :+1: It will be great for the community.

Guillaume

**Comment by hseeberger** [comment]
I prefer your implementation of Play JSON support over mine. So I'm asking whether you want to keep your project around or merge it into mine. BTW, I'm not sure what I want ;-)

**Comment by guillaumebreton** [comment]
Ok :) I will keep this project around and update it with the next play-json release.
